version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      spring_profiles_active: local
      spring_datasource_url: 'jdbc:postgresql://postgres:5432/moviedb'
      spring_datasource_username: postgres
      spring_datasource_password: postgresql
    ports:
      - '8080:8080'
    networks:
      - app-network
  taurus:
    image: blazemeter/taurus
    networks:
      - app-network
    volumes:
      - './:/bzt-configs'
  postgres:
    image: 'postgres:12'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: moviedb
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

networks:
  app-network:
volumes:
  postgres-data:
